project_name: custom-metrics-circonus-adapter

before:
    hooks:
        - go mod tidy
        
builds:
    -
        main: adapter.go
        binary: sbin/adapter
        env:
            - CGO_ENABLED=0
            - GODEBUG=netdns=go
        flags: 
            - -mod=vendor
        goos:
            - linux
        goarch:
            - amd64
        ignore:
            -
                goarch: 386
        ldflags:
            - -w
            - -extldflags "-static"
dockers:
    -
        goos: linux
        goarch: amd64
        goarm: ''
        binaries:
            - sbin/adapter
        image_templates:
            - "circonuslabs/{{.ProjectName}}:{{.Tag}}"
            - "circonuslabs/{{.ProjectName}}:latest"
        skip_push: false
        dockerfile: Dockerfile
        build_flag_templates:
            - "--label=org.label-schema.schema-version=1.0"
            - "--label=org.label-schema.version={{.Version}}"
            - "--label=org.label-schema.name={{.ProjectName}}"

archives:
    -   
        id: default
        name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}_{{.Arch}}"
        format: tar.gz
        replacements:
            amd64: x86_64
        files:
            - LICENSE
            - README.md
            - CHANGELOG.md

release:
    github:
        owner: circonus-labs
        name: custom-metrics-circonus-adapter
    draft: false
    prerelease: auto

snapshot:
    name_template: SNAPSHOT-{{.Commit}}

checksum:
    name_template: "{{.ProjectName}}_checksums.txt"
